default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: weather_api_development
  username: <%= ENV['DB_USERNAME'] || nil %>
  password: <%= ENV['DB_PASSWORD'] || nil %>
  host: <%= ENV['DB_HOST'] || nil %>

test:
  <<: *default
  database: weather_api_test

production:
  <<: *default
  database: weather_api_production
  username: weather_api
  password: <%= ENV["WEATHER_API_DATABASE_PASSWORD"] %>
